import { Router, type IRouter } from "express";
import healthRouter        from "./health";
import jobsRouter          from "./jobs";
import statsRouter         from "./stats";
import arbitrageRouter     from "./arbitrage";
import referralRouter      from "./referral";
import billingRouter       from "./billing";
import agentRouter         from "./agent";
import analyzeRouter       from "./analyze";
import vulnerabilitiesRouter from "./vulnerabilities";
import activityRouter      from "./activity";
import monetizationRouter  from "./monetization";
import tonRouter           from "./ton-routes";
import aiEvolutionRouter   from "./ai-evolution";
import webhookRouter       from "./webhook";
import nexusRouter         from "./nexus";
import dashboardRouter     from "./dashboard";
import telegramRouter      from "./telegram";
import tonRouter2          from "./ton";
import creatorRouter       from "./creator";
import developerRouter     from "./developer";
import creatorAiRouter     from "./creator-ai";
import agentsRouter        from "./agents";
import autotradeRouter     from "./autotrade";
import secretsRouter       from "./secrets";
import mirrorRouter        from "./mirror";
import vaultRouter         from "./vault";
import binanceRouter       from "./binance";
import tonInfraRouter      from "./ton-infra";
import nexusModelsRouter   from "./nexus-models";
import tonLiveRouter       from "./ton-live";
import authRouter           from "./auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(jobsRouter);
router.use(statsRouter);
router.use(arbitrageRouter);
router.use(referralRouter);
router.use(billingRouter);
router.use(agentRouter);
router.use(analyzeRouter);
router.use(vulnerabilitiesRouter);
router.use(activityRouter);
router.use(monetizationRouter);
router.use(tonRouter);
router.use(aiEvolutionRouter);
router.use(webhookRouter);
router.use(nexusRouter);
router.use(dashboardRouter);
router.use(telegramRouter);
router.use(tonRouter2);
router.use(creatorRouter);
router.use(developerRouter);
router.use(creatorAiRouter);
router.use(agentsRouter);
router.use(autotradeRouter);
router.use(secretsRouter);
router.use(mirrorRouter);
router.use(vaultRouter);
router.use(binanceRouter);
router.use(tonInfraRouter);
router.use(nexusModelsRouter);
router.use(tonLiveRouter);
router.use(authRouter);

export default router;
